[phases.setup]
nixPkgs = [
    "php82",
    "php82Extensions.mysqli",
    "php82Extensions.pdo_mysql",
    "php82Extensions.pdo",
    "php82Extensions.mbstring",
    "php82Extensions.session",
    "caddy"
]

[phases.build]
cmds = []

[start]
cmd = "php-fpm82 -D && caddy run --config /app/Caddyfile"
